variables:
  TF_ROOT: "terraform"
  TF_STATE_NAME: "default"
  MINIKUBE_PROFILE: "music-streaming"
  IMAGE_TAG: $CI_COMMIT_SHA

stages:
  - build
  - validate
  - plan
  - apply-vault
  - seed-vault
  - apply-all
  - debug

include: '.gitlab-ci-jobs.yml'