stages:
  - build

.build-template:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd $SERVICE_PATH
    - docker build -t $$CI_REGISTRY/$CI_PROJECT_PATH/$SERVICE_NAME:$CI_COMMIT_SHA .
    - docker push $$CI_REGISTRY/$CI_PROJECT_PATH/$SERVICE_NAME:$CI_COMMIT_SHA
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes:
        - $$SERVICE_PATH/**/*

build-users-auth:
  extends: .build-template
  variables:
    SERVICE_NAME: "users-auth"
    SERVICE_PATH: "services/business/users-auth"

build-users-account:
  extends: .build-template
  variables:
    SERVICE_NAME: "users-account"
    SERVICE_PATH: "services/business/users-account"