variables:
  TF_ROOT: "terraform"
  TF_STATE_NAME: "default"
  MINIKUBE_PROFILE: "music-streaming"
  IMAGE_TAG: $CI_COMMIT_SHA

stages:
  - setup-certs
  - build
  - setup
  - validate
  - plan
  - apply-platform
  - seed-vault
  - plan-apps
  - apply-apps
  - debug

include: '.gitlab-ci-jobs.yml'