# --- TEMPLATES ---

.infra-template-before-script-commands: &infra_template_before_script_commands
  - | # All commands consolidated into one block for consistent execution and `set -e`
    set -e # This now applies to all subsequent commands in this block
    cd ${TF_ROOT}
    export TF_HTTP_USERNAME="gitlab-ci-token"
    export TF_HTTP_PASSWORD="${CI_JOB_TOKEN}"
    export GITLAB_TF_ADDRESS=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${TF_STATE_NAME}
    terraform init -reconfigure -upgrade \
      -backend-config="address=${GITLAB_TF_ADDRESS}" \
      -backend-config="lock_address=${GITLAB_TF_ADDRESS}/lock" \
      -backend-config="unlock_address=${GITLAB_TF_ADDRESS}/lock" \
      -backend-config="lock_method=POST" \
      -backend-config="unlock_method=DELETE" \
      -backend-config="retry_wait_min=5"

.build-template:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - cd $SERVICE_PATH
    - docker build --progress=plain -t $CI_REGISTRY/$CI_PROJECT_PATH/$SERVICE_NAME:$IMAGE_TAG .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/$SERVICE_NAME:$IMAGE_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: on_success

# minikube delete -p $MINIKUBE_PROFILE || true
.infra-template:
  image:
    name: registry.gitlab.com/gitlab-org/terraform-images/stable
    entrypoint: [""]
  tags:
    - firstvds
  before_script:
      - *infra_template_before_script_commands

.vault-connection-script-commands: &vault_connection_script_commands
  - echo "Configuring Vault connection..."
  - kubectl port-forward svc/vault 8200:8200 &
  - sleep 5
  - export VAULT_ADDR='http://127.0.0.1:8200'
  - export VAULT_TOKEN='root'

.vault-connection-template:
  before_script:
    - *vault_connection_script_commands

# --- JOB DEFINITIONS ---

build-users-auth:
  extends: .build-template
  variables: { SERVICE_NAME: "users-auth", SERVICE_PATH: "services/business/users-auth" }

build-users-account:
  extends: .build-template
  variables: { SERVICE_NAME: "users-account", SERVICE_PATH: "services/business/users-account" }

setup-cluster:
  stage: setup
  image: registry.gitlab.com/gitlab-org/terraform-images/stable
  tags: 
    - firstvds
  script:
    - set -e
    - minikube delete -p $MINIKUBE_PROFILE || true
    - echo "Starting a fresh Minikube cluster..."
    - minikube start --memory=6656 --cpus=4 --driver=docker -p $MINIKUBE_PROFILE --wait=all
    - minikube update-context -p $MINIKUBE_PROFILE

validate:
  extends: .infra-template
  stage: validate
  needs:
    - setup-cluster
  script:
    - terraform validate

plan-platform:
  extends: .infra-template
  stage: plan
  needs:
    - setup-cluster
  script:
    - terraform plan -out="platform.tfplan" -target=helm_release.vault -target=helm_release.postgres -target=helm_release.redis -target=helm_release.kafka
  artifacts:
    paths:
      - "${TF_ROOT}/platform.tfplan"
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

apply-platform:
  extends: .infra-template
  stage: apply-platform
  script:
    - terraform apply -input=false "platform.tfplan"
  needs:
    - job: plan-platform
      artifacts: true
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual

seed-vault:
  extends: 
    - .infra-template
    - .vault-connection-template
  stage: seed-vault
  needs: 
     - job: apply-platform
  script:
    - vault login $VAULT_TOKEN
    - echo "Seeding secrets for Postgres..."
    - |
      vault kv put secret/data/platform/postgres \
        admin_password="$GITLAB_VAR_POSTGRES_ADMIN_PASS" \
        auth_db_name="users_auth_db" \
        auth_db_user="auth_user" \
        auth_db_pass="$GITLAB_VAR_AUTH_DB_PASS" \
        account_db_name="users_account_db" \
        account_db_user="account_user" \
        account_db_pass="$GITLAB_VAR_ACCOUNT_DB_PASS"
    - echo "Seeding secrets for Redis..."
    - vault kv put secret/data/platform/redis password="$GITLAB_VAR_REDIS_PASS"
    - echo "Writing secrets for users-auth..."
    - |
      vault kv put secret/data/users-auth db_url="$USERS_AUTH_POSTGRES_URL" \
                                     secret_key="$USERS_AUTH_SECRET_KEY" \
                                     client_id="$USERS_AUTH_CLIENT_ID" \
                                     redis_url="$USERS_AUTH_REDIS_URL" \
                                     access_token_expire_minutes="$ACCESS_TOKEN_EXPIRE_MINUTES" \
                                     refresh_token_expire_minutes="$REFRESH_TOKEN_EXPIRE_MINUTES"
    - echo "Writing secrets for users-account..."
    - |
      vault kv put secret/data/users-account db_url="USERS_ACCOUNT_PORTGRES_URL" \
                                        secret_key="$USERS_ACCOUNT_SECRET_KEY" \
                                        client_id="$USERS_ACCOUNT_CLIENT_ID" \
                                        redis_url="$USERS_ACCOUNT_REDIS_URL" \
                                        email="$USERS_ACCOUNT_EMAIL" \
                                        smtp_host="$USERS_ACCOUNT_SMTP_HOST" \
                                        smtp_port="$USERS_ACCOUNT_SMTP_PORT" \
                                        smtp_login="$USERS_ACCOUNT_SMTP_LOGIN" \
                                        smtp_password="$USERS_ACCOUNT_SMTP_PASSWORD" \
                                        email_confirmation_letter_expire_seconds="$USERS_ACCOUNT_EMAIL_COMFIRMATION_LETTER_EXPIRE_MINUTES"

    - kill %1
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

plan-apps:
  extends: 
    - .infra-template
    - .vault-connection-template
  stage: plan-apps
  needs:
    - job: seed-vault
  before_script:
    - *infra_template_before_script_commands
    - *vault_connection_script_commands
  script:
    - terraform plan -out="apps.tfplan"
  # after_script:
  #   - kill %1
  artifacts:
    paths:
      - "${TF_ROOT}/apps.tfplan"
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    
apply-apps:
  extends: .infra-template
  stage: apply-apps
  needs:
    - job: plan-apps
      artifacts: true
    - job: build-users-auth
    - job: build-users-account
    - job: seed-vault
  before_script:
    - *infra_template_before_script_commands
    - *vault_connection_script_commands
    - echo "Loading application images into Minikube..."
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - minikube image load $CI_REGISTRY/$CI_PROJECT_PATH/users-auth:$IMAGE_TAG
    - minikube image load $CI_REGISTRY/$CI_PROJECT_PATH/users-account:$IMAGE_TAG
  script:
    - terraform apply -input=false "apps.tfplan"
  # after_script:
  #   - kill %1
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

debug:
  extends: .infra-template
  stage: debug
  script:
    - kubectl get pods -o wide
    - |
      kubectl get pods --field-selector=status.phase!=Running,status.phase!=Succeeded -o jsonpath='{.items[*].metadata.name}' | xargs -r -n 1 kubectl describe pod
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual